### ISSUE TITLE
Jaco MoveIt deprecation error

### ISSUE THREAD

**Issue by sritee** [JenniferBuehler/jaco-arm-pkgs#14]
Deprecation warning: parameter 'allowed_execution_duration_scaling' moved into namespace 'trajectory_execution'.
Please, adjust file trajectory_execution.launch.xml!

When I try changing param in that file, I get the same error.
 Deprecation warning: parameter 'allowed_goal_duration_margin' moved into namespace 'trajectory_execution'.

My gazebo simulator is not moving according to the simulation in moveit, so I think this error may be the problem.

**Comment by JenniferBuehler** [comment]
That must be an update in MoveIt since I last used the packages.  I'd try in [trajectory_execution.launch.xml](https://github.com/JenniferBuehler/jaco-arm-pkgs/blob/master/jaco_tutorial/jaco_on_table_moveit/launch/trajectory_execution.launch.xml):

```xml
...
  <param name="trajectory_execution/allowed_execution_duration_scaling" value="1.2"/> <!-- default 1.2 -->
  <!-- Allow more than the expected execution time before triggering a trajectory cancel (applied after scaling) -->
  <param name="trajectory_execution/allowed_goal_duration_margin" value="100"/> <!-- default 0.5 -->
...
```

But if MoveIt has been updated there may be other follow-up errors. Probably I'll need to refresh the MoveIt files with the MoveIt setup assistant. You could always do that as well, as [described here](https://github.com/JenniferBuehler/jaco-arm-pkgs/wiki/Setup-Jaco-with-MoveIt), and replace the files in [jaco_on_file_moveit](https://github.com/JenniferBuehler/jaco-arm-pkgs/tree/master/jaco_tutorial/jaco_on_table_moveit) accordingly.

Let me know if it works with the XML edits I suggested, if there are other problems I'll look at it soon, though won't have the time this week, maybe next.

**Comment by JenniferBuehler** [comment]
I have updated the packages, now running on Melodic.  I haven't experienced this issue any more. So I'll close this now, since I haven't heard back.
Please re-open if required.
