### ISSUE TITLE
how to operate two jaco arms

### ISSUE THREAD

**Issue by deokisys** [JenniferBuehler/jaco-arm-pkgs#17]
hi 
thank you for your good jaco arm packages code.
I have question
I want to operate two arm separately.
How can I reach that goal?
thank you

**Comment by JenniferBuehler** [comment]
Hi,

this has been done before, but I haven't tested in in a while... I can have a look at my other computer later, meanwhile you can try the launch file [jaco_on_table_two_arms_gazebo.launch](https://github.com/JenniferBuehler/jaco-arm-pkgs/blob/master/jaco_tutorial/jaco_on_table/launch/jaco_on_table_two_arms_gazebo.launch). Does it still work (there have been updates to the needed packages since and haven't tried it again in a while)?

**Comment by AbhinavGupta1694** [comment]
Hi Jennifer,
I tried  the above mentioned launch file [jaco_on_table_two_arms_gazebo.launch](https://github.com/JenniferBuehler/jaco-arm-pkgs/blob/master/jaco_tutorial/jaco_on_table/launch/jaco_on_table_two_arms_gazebo.launch), it does work just to load two jaco arms onto the table.

In case I want to move the arms, I did not find any topic to publish the positions also no other way, please help me to know if we can also simulate it (movement of both the arms) through some script or anyway out.

**Comment by JenniferBuehler** [comment]
So sorry, I must have missed this response :(
Is this still relevant?

**Comment by JenniferBuehler** [comment]
Will close this for now, please re-open if still relevant.
