### ISSUE TITLE
Can't execute RobotTrajectory

### ISSUE THREAD

**Issue by ankitvora7** [JenniferBuehler/jaco-arm-pkgs#2]
Hi @JenniferBuehler,

First, thanks for the multidof controller. It should be quite useful. 
I'm trying to use the same to control a quadrotor in moveit. 
The problem I'm facing is that I am not able to run RobotTrajectoryExecutor. This is the error I'm getting.

[ERROR] [1460076394.851834890, 2231.848000000]: RobotTrajectoryExecutor: Joint trajectory action client not connected: /joint_trajectory_action
[ERROR] [1460076394.851876655, 2231.848000000]: RobotTrajectoryExecutor: Path execution action client not connected: /navigate_path
[ERROR] [1460076394.851910877, 2231.848000000]: RobotTrajecoryExecutor: Failed to connect to clients, hence can't execute RobotTrajectory
[ERROR] [1460076394.851933646, 2231.848000000]: Failed to send trajectory part 1 of 1 to controller no-name

I understand that there's not client for the Joint Trajectory Action and Path Execution Action. But my doubt is who should be the client for this action ? If I'm using a simulated robot, should this be gazebo ?
Can you throw some light on this please.

Ankit

**Comment by JenniferBuehler** [comment]
Hi Ankit,

the point of the multidof controller is to have at least joint trajectory action server running, which then executes the MoveIt motion plans. Because the motion plans can _additionally_ include a robot path the for virtual joint, I have added this controller which includes the path executor, because MoveIt's simple example controller does not handle such virtual joint movements.

MoveIt! is  mostly used for robot arms (or any kinematic chains for that matter), therefore I haven't made the joint trajectory action server optional... I may do this in the next update though, this is a simple change. Meanwhile, I guess you could make a "fake" joint trajectory action server which accepts joint trajectory actions but does nothing except return successfully. But then, you will still need a path execution action server to handle at least virtual joint movements, otherwise the multidof controller would do nothing (because it would then neither accept joint trajectories nor path actions). I have a simple path executor but that code is not yet ready to be published yet I'm afraid ;)

To suppress the error with the path execution action client, you would have to set the topic (which is set to the default "/navigate_path") to an empty string. You can do this in the ROS parameters, described [here](https://github.com/JenniferBuehler/moveit-pkgs/wiki/moveit_controller_multidof). But then again, this only makes sense if you have at least a joint trajectory action server running.

May I ask what you are trying to do? I'm guessing that for the quadrotor you need a path planner and path executor? Is there a particular reason why you want or need to use MoveIt for this? If you give me a few details I may be able to help you better ;)

Jennifer

**Comment by ankitvora7** [comment]
Hi Jennifer,

I'm basically trying to simulate 3D mapping and quadrotor navigation in a cluttered environment. So the modules that I have to take care of are mapping, localization, planning and control. The motivation behind using moveit was the unavailability of 3D navigation packages and that something like this had already been done with moveit (check this out: https://www.youtube.com/watch?v=VlBQLbmc03g).
My pipeline is almost ready wherein I have the mapping, localization and planning sorted out. Just that the obtained path needs to be executed by the quadrotor using a suitable controller. 
Do you have any suggestions ?

**Comment by JenniferBuehler** [comment]
I see. So you are trying to use MoveIt! as path planner using the virtual joint, as I guessed. In this case it makes sense to disable the joint trajectory client and only enable the path execution client.
I will make this change some time today. Meanwhile, this is what you will need: An action server which accepts messages of type path_navigation_msgs/PathExecution.action (in the repository general-message-pkgs, which you must have downloaded already).  In this action you will get a nav_msgs/Path.msg with the coordinates of the planned path by MoveIt!. Your action server then has to control the quadrotor to navigate those coordinates.

Jennifer

**Comment by ankitvora7** [comment]
Yup! You're right. The virtual joint is used to plan the quad path.
Let me know once you make the changes and commit the changes. Meanwhile
I'll work on the action server.
Thanks for the help Jennifer :)

**Comment by JenniferBuehler** [comment]
Alright so I've done the changes and now the joint trajectory server is optional.

I don't have a running set-up with a path execution ready at the moment (would have to port over my old example first), so can you please post any issues, if you have any? It should be fine as the change wasn't dramatic, but haven't tested it with only the path navigation on (only tested again with both servers off, and with only joint trajectory on).

It's best to post any more about this topic in the [moveit_msgs](https://github.com/JenniferBuehler/moveit-pkgs) repository, because that's where the package resides (you have to pull the moveit-pkgs repository for an update as well). Thanks!

Let me know how it goes.

**Comment by ankitvora7** [comment]
Thanks Jennifer. I'll use it soon and get back to you.

**Comment by JenniferBuehler** [comment]
Presuming this has been fixed as changes were trivial, and that possible future issues will be reported again. Closing for now.
