### ISSUE TITLE
catkin_make fails at/after test_set_joint_state_publisher_vel

### ISSUE THREAD

**Issue by saspelund** [JenniferBuehler/jaco-arm-pkgs#3]
[ 89%] Built target test_set_joint_state_publisher_vel
~/catkin_ws/src/jaco-arm-pkgs/jaco_arm/jaco_gazebo/src/JacoGazeboJointControlLocalImpl.cpp: In constructor ‘gazebo::JacoGazeboJointControlLocalImpl::JacoGazeboJointControlLocalImpl()’:
~/catkin_ws/src/jaco-arm-pkgs/jaco_arm/jaco_gazebo/src/JacoGazeboJointControlLocalImpl.cpp:84:44: error: cannot call member function ‘void gazebo::common::Console::SetQuiet(bool)’ without object
     gazebo::common::Console::SetQuiet(false);
                                            ^
make[2]: **\* [jaco-arm-pkgs/jaco_arm/jaco_gazebo/CMakeFiles/jaco_gazebo_joint_control.dir/src/JacoGazeboJointControlLocalImpl.cpp.o] Error 1
make[1]: **\* [jaco-arm-pkgs/jaco_arm/jaco_gazebo/CMakeFiles/jaco_gazebo_joint_control.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j4 -l4" failed

I am receiving the above error output when I try running catkin_make. My usual fix of simply running catkin_make again isn't working (I have very little idea as to what I am doing). Does it have to do with the version of Gazebo that is installed? I am using Gazebo 2.2.6 because that is the one that comes with ROS Indigo, but assuming everything else is equal and it helps, I could wipe off Indigo and install Jade to therefore use a later version of Gazebo.

OS: Ubuntu 14.04
ROS: Indigo
Gazebo: 2.2.6

**Comment by JenniferBuehler** [comment]
Ok, that's odd. I have the same system configuration so I've done a complete fresh re-build to see if I can reproduce it, and then got the same issue. Compiling a second time then fixed it. But that's not how it should be, so I fixed the problem in the cmake files.

The problem was that on the first compiler run, ASSIMP_LIBRARIES was not set, only ASSIMP_LIBRARY. Then on the second compile run, both variables were set. Another one of my packages must cache the cmake variable, not sure how the whole process works, but that's the only explanation I have at this point ;)

I've added both variables to the link target and now it compiles on the first run as well.
Can you try again and let me know if it works for you as well now?

Cheers
Jennifer

**Comment by JenniferBuehler** [comment]
Sorry I posted this in the wrong issue! Oups.
I'll get back to your message next.

**Comment by JenniferBuehler** [comment]
Oh. Thanks for reporting. That's because I recently added this line, and I'm currently testing on Jade with Gazebo 5. I've #ifndef'ed out this line, it should now work. Let me know!

Jennifer

**Comment by saspelund** [comment]
catkin_make was successful! 

Thank you very much!

P.S. I don't know if this is the right place for this question but, if all else is equal, should I just install and use Jade (I'm worried about support for other pkgs)? I am brand new to ROS and am using your program as a starting point so would it be better to run in parallel with you? Thanks!

**Comment by JenniferBuehler** [comment]
If you're worried about pkg support just stick to Indigo for now, it's the long term support version. Many packages are available for Jade, but some you still have to compile from source.
